### ISSUE TITLE
undeclared variable in Nano33BLESensorExample_gesture.ino

### ISSUE THREAD

**Issue by amorsch** [DaleGia/Nano33BLESensor#4]
Hello, 
in 
Nano33BLESensorExample_gesture.ino

you declare 

Nano33BLEGestureData gestureData;

but use in line 132

 if(Gesture.pop(proximityData))

**Comment by DaleGia** [comment]
Thanks for reporting this @amorsch. Classic copy and paste bug. Just cleaned it up. Will close this now.
