### ISSUE TITLE
Cannot use Nano33BLESensor microphone

### ISSUE THREAD

**Issue by Jesuscc9** [DaleGia/Nano33BLESensor#7]
I am following the codes of examples in the repo, but when I compile the acelerometer one, I get this error: 

```
Arduino\libraries\Nano33BLESensor\src\Nano33BLEMicrophoneRMS.cpp:29:10: fatal error: arm_math.h: No such file or directory
 #include <arm_math.h>

```

And when I install that [library ](https://github.com/PaulStoffregen/arm_math)manually, the error stills there.

**Comment by DaleGia** [comment]
Hi @Jesuscc9 

This issue only affects examples using arm_math.h, which are the cmsis arm math libraries. It is a known issue and some ways to solve it can be found in the only other current issue in this repository. 

I am currently wait to have to to manually add these cmsis arm math libraries to this repo as another way to solve this issue,  and this fix will he included in the next release.
