### ISSUE TITLE
Error while running all the programs

### ISSUE THREAD

**Issue by raghavendrajain** [DaleGia/Nano33BLESensor#8]
No matter what program I run, I always get the following error

```
exit status 1
call of overloaded 'writeValue(char [20], int&)' is ambiguous
```

For example, for accelerometer example, the following is the error 

```
In file included from /home/raghav/Arduino/libraries/Nano33BLESensor/src/Nano33BLEAccelerometer.h:33:0,
                 from /home/raghav/Arduino/libraries/Nano33BLESensor/examples/Nano33BLESensorExample_accelerometer/Nano33BLESensorExample_accelerometer.ino:32:
/home/raghav/Arduino/libraries/Nano33BLESensor/src/Nano33BLESensorBuffer.h:55:15: error: 'CircularBuffer' in namespace 'mbed' does not name a template type
         mbed::CircularBuffer<T, BUFFER_SIZE> buffer;
               ^~~~~~~~~~~~~~
/home/raghav/Arduino/libraries/Nano33BLESensor/examples/Nano33BLESensorExample_accelerometer/Nano33BLESensorExample_accelerometer.ino: In function 'void loop()':
Nano33BLESensorExample_accelerometer:142:68: error: call of overloaded 'writeValue(char [20], int&)' is ambiguous
                 accelerometerXBLE.writeValue(bleBuffer, writeLength); 
                                                                    ^
In file included from /home/raghav/Arduino/libraries/ArduinoBLE/src/BLEService.h:23:0,
                 from /home/raghav/Arduino/libraries/ArduinoBLE/src/BLEDevice.h:25,
                 from /home/raghav/Arduino/libraries/ArduinoBLE/src/local/BLELocalDevice.h:23,
                 from /home/raghav/Arduino/libraries/ArduinoBLE/src/ArduinoBLE.h:23,
                 from /home/raghav/Arduino/libraries/Nano33BLESensor/examples/Nano33BLESensorExample_accelerometer/Nano33BLESensorExample_accelerometer.ino:30:
/home/raghav/Arduino/libraries/ArduinoBLE/src/BLECharacteristic.h:72:7: note: candidate: int BLECharacteristic::writeValue(const void*, int, bool)
   int writeValue(const void* value, int length, bool withResponse = true);
       ^~~~~~~~~~
/home/raghav/Arduino/libraries/ArduinoBLE/src/BLECharacteristic.h:73:7: note: candidate: int BLECharacteristic::writeValue(const char*, bool)
   int writeValue(const char* value, bool withResponse = true);
       ^~~~~~~~~~
Nano33BLESensorExample_accelerometer:144:68: error: call of overloaded 'writeValue(char [20], int&)' is ambiguous
                 accelerometerYBLE.writeValue(bleBuffer, writeLength);      
                                                                    ^
In file included from /home/raghav/Arduino/libraries/ArduinoBLE/src/BLEService.h:23:0,
                 from /home/raghav/Arduino/libraries/ArduinoBLE/src/BLEDevice.h:25,
                 from /home/raghav/Arduino/libraries/ArduinoBLE/src/local/BLELocalDevice.h:23,
                 from /home/raghav/Arduino/libraries/ArduinoBLE/src/ArduinoBLE.h:23,
                 from /home/raghav/Arduino/libraries/Nano33BLESensor/examples/Nano33BLESensorExample_accelerometer/Nano33BLESensorExample_accelerometer.ino:30:
/home/raghav/Arduino/libraries/ArduinoBLE/src/BLECharacteristic.h:72:7: note: candidate: int BLECharacteristic::writeValue(const void*, int, bool)
   int writeValue(const void* value, int length, bool withResponse = true);
       ^~~~~~~~~~
/home/raghav/Arduino/libraries/ArduinoBLE/src/BLECharacteristic.h:73:7: note: candidate: int BLECharacteristic::writeValue(const char*, bool)
   int writeValue(const char* value, bool withResponse = true);
       ^~~~~~~~~~
Nano33BLESensorExample_accelerometer:146:68: error: call of overloaded 'writeValue(char [20], int&)' is ambiguous
                 accelerometerZBLE.writeValue(bleBuffer, writeLength);      
                                                                    ^
In file included from /home/raghav/Arduino/libraries/ArduinoBLE/src/BLEService.h:23:0,
                 from /home/raghav/Arduino/libraries/ArduinoBLE/src/BLEDevice.h:25,
                 from /home/raghav/Arduino/libraries/ArduinoBLE/src/local/BLELocalDevice.h:23,
                 from /home/raghav/Arduino/libraries/ArduinoBLE/src/ArduinoBLE.h:23,
                 from /home/raghav/Arduino/libraries/Nano33BLESensor/examples/Nano33BLESensorExample_accelerometer/Nano33BLESensorExample_accelerometer.ino:30:
/home/raghav/Arduino/libraries/ArduinoBLE/src/BLECharacteristic.h:72:7: note: candidate: int BLECharacteristic::writeValue(const void*, int, bool)
   int writeValue(const void* value, int length, bool withResponse = true);
       ^~~~~~~~~~
/home/raghav/Arduino/libraries/ArduinoBLE/src/BLECharacteristic.h:73:7: note: candidate: int BLECharacteristic::writeValue(const char*, bool)
   int writeValue(const char* value, bool withResponse = true);
       ^~~~~~~~~~
In file included from /home/raghav/Arduino/libraries/Nano33BLESensor/src/Nano33BLEAccelerometer.h:33:0,
                 from /home/raghav/Arduino/libraries/Nano33BLESensor/examples/Nano33BLESensorExample_accelerometer/Nano33BLESensorExample_accelerometer.ino:32:
/home/raghav/Arduino/libraries/Nano33BLESensor/src/Nano33BLESensorBuffer.h: In instantiation of 'bool Nano33BLESensorBuffer<T>::pop(T&) [with T = Nano33BLEAccelerometerData]':
/home/raghav/Arduino/libraries/Nano33BLESensor/examples/Nano33BLESensorExample_accelerometer/Nano33BLESensorExample_accelerometer.ino:134:51:   required from here
/home/raghav/Arduino/libraries/Nano33BLESensor/src/Nano33BLESensorBuffer.h:68:18: error: 'class Nano33BLESensorBuffer<Nano33BLEAccelerometerData>' has no member named 'buffer'
     return this->buffer.pop(buffer);
            ~~~~~~^~~~~~
exit status 1
call of overloaded 'writeValue(char [20], int&)' is ambiguous
```

**Comment by Bartolomeus76** [comment]
Same here, impossible to compile any of them without rewriting the whole code.

**Comment by DaleGia** [comment]
Hi @raghavendrajain and @Bartolomeus76 ,

This is possible due to version issues with Arduino BLE, or the version of the latest Arduino Mbed Core. 

This library is probably overdue for a bit of an update to make sure things work with the latest versions of this library. I will be trying to make time for this over the next month or so.

If you have managed to find fixes in the mean time, I would ask you to share them in the spirit of open source.

Thanks for pointing out this issue!

**Comment by Duodecan** [comment]
same here ...

In file included from /Users/adm/Downloads/EKRAN_GPS__3.5_WORKX/EKRAN_GPS__3.5_WORKX.ino:1:0:
/Users/adm/Documents/Arduino/libraries/Nano33BLESensor-master/src/Nano33BLEPressure.h:88:7: error: 'osPriority' has not been declared
       osPriority threadPriority = osPriorityNormal,

       ^~~~~~~~~~
/Users/adm/Documents/Arduino/libraries/Nano33BLESensor-master/src/Nano33BLEPressure.h:116:5: error: 'rtos' does not name a type; did you mean 'utoa'?
     rtos::Thread readThread;

     ^~~~
     utoa
/Users/adm/Documents/Arduino/libraries/Nano33BLESensor-master/src/Nano33BLEPressure.h:88:35: error: 'osPriorityNormal' was not declared in this scope
       osPriority threadPriority = osPriorityNormal,

                                   ^~~~~~~~~~~~~~~~
/Users/adm/Documents/Arduino/libraries/Nano33BLESensor-master/src/Nano33BLEPressure.h:88:35: note: suggested alternative: 'osPriority'
       osPriority threadPriority = osPriorityNormal,

                                   ^~~~~~~~~~~~~~~~
                                   osPriority
/Users/adm/Documents/Arduino/libraries/Nano33BLESensor-master/src/Nano33BLEPressure.h: In member function 'void Nano33BLEPressure::begin()':
/Users/adm/Documents/Arduino/libraries/Nano33BLESensor-master/src/Nano33BLEPressure.h:83:7: error: 'readThread' was not declared in this scope
       readThread.start(mbed::callback(Nano33BLEPressure::readFunction, this));

       ^~~~~~~~~~
/Users/adm/Documents/Arduino/libraries/Nano33BLESensor-master/src/Nano33BLEPressure.h:83:7: note: suggested alternative: 'readPeriod'
       readThread.start(mbed::callback(Nano33BLEPressure::readFunction, this));

       ^~~~~~~~~~
       readPeriod
/Users/adm/Documents/Arduino/libraries/Nano33BLESensor-master/src/Nano33BLEPressure.h: In constructor 'Nano33BLEPressure::Nano33BLEPressure(uint32_t, int, uint32_t)':
/Users/adm/Documents/Arduino/libraries/Nano33BLESensor-master/src/Nano33BLEPressure.h:91:9: error: class 'Nano33BLEPressure' does not have any field named 'readThread'
         readThread(

         ^~~~~~~~~~
In file included from /Users/adm/Downloads/EKRAN_GPS__3.5_WORKX/EKRAN_GPS__3.5_WORKX.ino:2:0:
/Users/adm/Documents/Arduino/libraries/Nano33BLESensor-master/src/Nano33BLETemperature.h: At global scope:
/Users/adm/Documents/Arduino/libraries/Nano33BLESensor-master/src/Nano33BLETemperature.h:88:7: error: 'osPriority' has not been declared
       osPriority threadPriority = osPriorityNormal,

       ^~~~~~~~~~
/Users/adm/Documents/Arduino/libraries/Nano33BLESensor-master/src/Nano33BLETemperature.h:117:5: error: 'rtos' does not name a type; did you mean 'utoa'?
     rtos::Thread readThread;

     ^~~~
     utoa
/Users/adm/Documents/Arduino/libraries/Nano33BLESensor-master/src/Nano33BLETemperature.h:88:35: error: 'osPriorityNormal' was not declared in this scope
       osPriority threadPriority = osPriorityNormal,

                                   ^~~~~~~~~~~~~~~~
/Users/adm/Documents/Arduino/libraries/Nano33BLESensor-master/src/Nano33BLETemperature.h:88:35: note: suggested alternative: 'osPriority'
       osPriority threadPriority = osPriorityNormal,

                                   ^~~~~~~~~~~~~~~~
                                   osPriority
/Users/adm/Documents/Arduino/libraries/Nano33BLESensor-master/src/Nano33BLETemperature.h: In member function 'void Nano33BLETemperature::begin()':
/Users/adm/Documents/Arduino/libraries/Nano33BLESensor-master/src/Nano33BLETemperature.h:83:7: error: 'readThread' was not declared in this scope
       readThread.start(mbed::callback(Nano33BLETemperature::readFunction, this));

       ^~~~~~~~~~
/Users/adm/Documents/Arduino/libraries/Nano33BLESensor-master/src/Nano33BLETemperature.h:83:7: note: suggested alternative: 'readPeriod'
       readThread.start(mbed::callback(Nano33BLETemperature::readFunction, this));

       ^~~~~~~~~~
       readPeriod
/Users/adm/Documents/Arduino/libraries/Nano33BLESensor-master/src/Nano33BLETemperature.h: In constructor 'Nano33BLETemperature::Nano33BLETemperature(uint32_t, int, uint32_t)':
/Users/adm/Documents/Arduino/libraries/Nano33BLESensor-master/src/Nano33BLETemperature.h:91:9: error: class 'Nano33BLETemperature' does not have any field named 'readThread'
         readThread(

         ^~~~~~~~~~
In file included from /Users/adm/Downloads/EKRAN_GPS__3.5_WORKX/EKRAN_GPS__3.5_WORKX.ino:3:0:
/Users/adm/Documents/Arduino/libraries/Nano33BLESensor-master/src/Nano33BLEGyroscope.h: At global scope:
/Users/adm/Documents/Arduino/libraries/Nano33BLESensor-master/src/Nano33BLEGyroscope.h:90:7: error: 'osPriority' has not been declared
       osPriority threadPriority = osPriorityNormal,

**Comment by ControlxFreak** [comment]
I'm also having the exact same problems with the examples.

**Comment by DaleGia** [comment]
Hi. This is related to the issue where the library only ran on the now depreciated Arduino Mbed Core and has been known for a while. I have now updated the library so it compiles on the latest core. I just need to test it a bit more thoroughly before making it a new release, but this should happen in the next week.
